/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.EStatut;
import beans.Etudiant;
import beans.EmpruntLivre;
import beans.Livre;
import java.util.Date;
import services.EmpruntService;
import services.EtudiantService;
import services.LivreService;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author box
 */
public class EmpruntForm extends javax.swing.JInternalFrame {

    private LivreService ls;
    private EtudiantService es;
    private EmpruntService emps;
    private EStatut est;
    private JComboBox<String> statutEmprunt;

    private DefaultTableModel model;

    /**
     * Creates new form EmpruntForm
     */
    public EmpruntForm() {
        initComponents();
        ls = new LivreService();
        es = new EtudiantService();
        emps = new EmpruntService();
        est = EStatut.EN_COURS;
        statutEmprunt = new JComboBox<>();
        model = (DefaultTableModel) empruntListe.getModel();
        loadLivre();
        loadEtudiant();
        loadStatu();

        load();
    }

    void loadLivre() {
        for (Livre l : ls.findAll()) {
            ListeLivre.addItem(l);
        }
    }

    void loadEtudiant() {
        for (Etudiant e : es.findAll()) {
            ListeEtudiant.addItem(e);
        }
    }

    void loadStatu() {
        if (statutEmprunt == null) {
         System.out.println("statut Emprunt est null !");
         } else {
         statutEmprunt.removeAllItems();
         for (EStatut s : EStatut.values()) {
         ListeStatu.addItem(s.name());
         }
         }
        ListeStatu.removeAllItems();
        for (EStatut s : EStatut.values()) {
            ListeStatu.addItem(s.name());
        }

    }

    void load() {
        model.setRowCount(0);
        for (EmpruntLivre e : emps.findAll()) {
            if (e == null) {
                System.out.println("Avertissement : Un emprunt est null.");
                continue;
            }

            String titreLivre = (e.getLivre() != null) ? e.getLivre().getTitre() : "Livre inconnu";
            String nomEtudiant = (e.getEtudiant() != null) ? e.getEtudiant().getNom() : "Étudiant inconnu";

            model.addRow(new Object[]{
                titreLivre,
                nomEtudiant,
                e.getDateEmprunt(),
                e.getDateRetour(),
                e.getStatut()
            });
        }
    }

    void enregistrerEmprunt() {
        String selectedStatut = (String) statutEmprunt.getSelectedItem();
        est = EStatut.valueOf(selectedStatut);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bnAdd = new javax.swing.JButton();
        ListeLivre = new javax.swing.JComboBox();
        ListeEtudiant = new javax.swing.JComboBox();
        ListeStatu = new javax.swing.JComboBox();
        date_Emprunt = new com.toedter.calendar.JDateChooser();
        date_Retour = new com.toedter.calendar.JDateChooser();
        bnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empruntListe = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("informations Livres"));
        jPanel1.setToolTipText("");

        jLabel1.setText("Livre :");

        jLabel2.setText("Etudiant :");

        jLabel3.setText("dateEmprunt :");

        jLabel4.setText("dateRetour :");

        jLabel5.setText("statut :");

        bnAdd.setText("Enregistrer");
        bnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAddActionPerformed(evt);
            }
        });

        ListeLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeLivreActionPerformed(evt);
            }
        });

        ListeEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeEtudiantActionPerformed(evt);
            }
        });

        bnDelete.setText("Supprimer");
        bnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ListeStatu, 0, 122, Short.MAX_VALUE)
                    .addComponent(ListeLivre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListeEtudiant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(date_Emprunt, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(date_Retour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bnDelete)
                        .addGap(35, 35, 35)
                        .addComponent(bnAdd)
                        .addGap(42, 42, 42))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(date_Emprunt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(date_Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bnAdd)
                            .addComponent(bnDelete)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(ListeLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(ListeEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ListeStatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des emprunts"));

        empruntListe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Livre", "Etudiant", "dateEmprunt", "dateRetour", "Statu"
            }
        ));
        jScrollPane1.setViewportView(empruntListe);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAddActionPerformed
        Livre livre = (Livre) ListeLivre.getSelectedItem();
        Etudiant etudiant = (Etudiant) ListeEtudiant.getSelectedItem();

        String selectedStatut = (String) ListeStatu.getSelectedItem();


        Date dateEmprunt = date_Emprunt.getDate();
        Date dateRetour = date_Retour.getDate();

        if (livre == null || etudiant == null || dateEmprunt == null || dateRetour == null) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs.", "Avertissement", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (emps.create(new EmpruntLivre(EStatut.EN_COURS, dateEmprunt, dateRetour, livre, etudiant))) {
            JOptionPane.showMessageDialog(this, "enregistré avec succès");
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de l'enregistrement de l'emprunt.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        load();

    }//GEN-LAST:event_bnAddActionPerformed

    private void ListeLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeLivreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListeLivreActionPerformed

    private void ListeEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListeEtudiantActionPerformed

    private void bnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnDeleteActionPerformed
        int selectedRow = empruntListe.getSelectedRow();

    if (selectedRow != -1) {
        // Obtenir l'objet emprunt à partir de la table
        String titreLivre = (String) empruntListe.getValueAt(selectedRow, 0);
        String nomEtudiant = (String) empruntListe.getValueAt(selectedRow, 1);

        // Confirmer la suppression
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer cet emprunt de " 
                + titreLivre + " par " + nomEtudiant + " ?", "Confirmer la suppression", JOptionPane.YES_NO_OPTION);

        if (reponse == JOptionPane.YES_OPTION) {
            // Trouver l'emprunt correspondant dans la base de données et le supprimer
            EmpruntLivre empruntToDelete = emps.findByLivreAndEtudiant(titreLivre, nomEtudiant);
            if (emps.delete(empruntToDelete)) {
                JOptionPane.showMessageDialog(this, "Emprunt supprimé avec succès.");
                load(); // Rafraîchir la table
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la suppression de l'emprunt.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un emprunt à supprimer.", "Avertissement", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_bnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ListeEtudiant;
    private javax.swing.JComboBox ListeLivre;
    private javax.swing.JComboBox ListeStatu;
    private javax.swing.JButton bnAdd;
    private javax.swing.JButton bnDelete;
    private com.toedter.calendar.JDateChooser date_Emprunt;
    private com.toedter.calendar.JDateChooser date_Retour;
    private javax.swing.JTable empruntListe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /*private void load() {
     throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
     }*/
}
