/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import connexion.Connexion;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.title.TextTitle;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;

/**
 *
 * @author box
 */
public class GraphiqueEmprunts extends javax.swing.JInternalFrame {

    /**
     * Creates new form GraphiqueEmprunts
     */
    public GraphiqueEmprunts() {
        //initComponents();
        setTitle("Taux d'Emprunt par Catégorie");
        setSize(900, 800);
        setLocation(50, 50);

        JFreeChart chart = ChartFactory.createPieChart(
                "Taux d'Emprunt par Catégorie",
                getDataset(),
                true,
                true,
                false
        );
        customizeChart(chart);

        ChartPanel panel = new ChartPanel(chart);
        setContentPane(panel);

        setResizable(true);
        setMaximizable(true);
        setClosable(true);
    }

    private DefaultPieDataset getDataset() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        Connection connexion = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;

        try {
            connexion = Connexion.getInstance().getCn();

            if (connexion == null || connexion.isClosed()) {
                System.out.println("Erreur : Connexion fermée !");
                return dataset; // Retourne un dataset vide pour éviter l'erreur
            }

            String sql = "SELECT categorie, COUNT(*) as total FROM livre GROUP BY categorie";
            stmt = connexion.prepareStatement(sql);
            rs = stmt.executeQuery();

            while (rs.next()) {
                String categorie = rs.getString("categorie");
                int total = rs.getInt("total");
                dataset.setValue(categorie, total);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                // Ne pas fermer la connexion ici si elle doit être réutilisée
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        return dataset;
    }

    private void customizeChart(JFreeChart chart) {
        TextTitle title = new TextTitle("Taux d'Emprunt par Catégorie de Livres");
        title.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        title.setPaint(Color.BLUE);
        chart.setTitle(title);

        PiePlot plot = (PiePlot) chart.getPlot();
        plot.setBackgroundPaint(new Color(240, 240, 240));
        plot.setSectionPaint(0, new Color(255, 182, 193));
        plot.setSectionPaint(1, new Color(176, 224, 230));
        plot.setSectionPaint(2, new Color(255, 255, 204));
        plot.setSectionPaint(3, new Color(144, 238, 144)); // Pastel Green
        plot.setSectionPaint(4, new Color(255, 224, 178));
        plot.setLabelFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12));
        plot.setLabelPaint(Color.BLACK);
        plot.setLabelBackgroundPaint(Color.WHITE);
        plot.setLabelFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12));
        plot.setLabelPaint(Color.BLACK);
        plot.setLabelBackgroundPaint(Color.WHITE);

        plot.setLabelGenerator(new StandardPieSectionLabelGenerator(
                "{0}: {1} ({2})",
                new java.text.DecimalFormat("0"),
                new java.text.DecimalFormat("0%")
        ));
        chart.getLegend().setBackgroundPaint(new Color(220, 220, 220));
        chart.getLegend().setItemFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
